### PR TITLE
Added multilingual support, and added Chinese translation

### PR DESCRIPTION
**Pull request by TiomTang**
Added multilingual support, and added Chinese translation

### CODE REVIEW

**Comment by bhayden53** [comment]
Can you change the target branch to dev?

**Comment by Misunderstood-Wookiee** [comment]
Yaay someone made translations, yes please target branch dev and this can
be merged.

**Comment by bhayden53** [comment]
yes this is EXTREMELY appreciated

**Comment by TiomTang** [comment]
Yes, I have changed to the DEV branch

**Comment by Misunderstood-Wookiee** [comment]
@bhayden53 
You made mention that https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/pull/124 was going to conflict with this but that is merged into Dev and currently I am not seeing this with any conflict on my end.. can you confirm? 

I think you just mean the extra param won't use the language files but that is a fairly easy fix I just don't know the languages used in the translations to add a new translation.

**Comment by bhayden53** [comment]
There's a new param in supply mule that needs a string added. I did think it would conflict, but I guess it's not because I added it and it didn't touch anything changed in this PR.

So if you merge this, that one new param will also need a translation.

**Comment by TiomTang** [comment]
@bhayden53 
I think this is not a problem. I will follow up and translate this new parameter after the merger.

**Comment by bhayden53** [comment]
FWIW I copied the param from travel mule so the string may even be exactly the same

**Comment by Misunderstood-Wookiee** [comment]
I see well the merger of the patch which need translations is already
merged in development branch I just have not merged this yet until feedback

**Comment by Misunderstood-Wookiee** [comment]
Merged anyway if it needs a fix can hotfix it later.

**Pull request merged**
