### PR TITLE
Dev

### LINKED ISSUE #85: [Potential Bug]: Idle mules cause the game to hang intermittently?
**Describe the Bug**
The game hangs intermittently (<1fps) for a couple seconds, then goes back to normal.
Error clumps like this appear suspiciously at the time the game hangs:
`[General] 161169.10 ======================================
[=ERROR=] 161169.10 AIDirector::Move(): Possibly infinite wake request loop: mule.lib.evaluate_tradeoffers on entity 0x1bd13, wake reason mask=0001 (Most likely cause: Script starts and returns immediately)
[General] 161169.10 ======================================
[General] 161170.12 ======================================
[=ERROR=] 161170.12 AIDirector::Move(): Possibly infinite wake request loop: mule.lib.evaluate_tradeoffers on entity 0x5d27d, wake reason mask=0001 (Most likely cause: Script starts and returns immediately)
[General] 161170.12 ======================================
[General] 161170.12 ======================================
[=ERROR=] 161170.12 AIDirector::Move(): Possibly infinite wake request loop: mule.lib.evaluate_tradeoffers on entity 0x4ce24, wake reason mask=0001 (Most likely cause: Script starts and returns immediately)
[General] 161170.12 ======================================
[General] 161170.12 ======================================
[=ERROR=] 161170.12 AIDirector::Move(): Possibly infinite wake request loop: mule.lib.evaluate_tradeoffers on entity 0x1afdf, wake reason mask=0001 (Most likely cause: Script starts and returns immediately)
[General] 161170.12 ======================================
[General] 161171.12 ======================================
[=ERROR=] 161171.12 AIDirector::Move(): Possibly infinite wake request loop: mule.lib.evaluate_tradeoffers on entity 0x4f74e, wake reason mask=0001 (Most likely cause: Script starts and returns immediately)
[General] 161171.12 ======================================
[General] 161172.12 ======================================
[=ERROR=] 161172.12 AIDirector::Move(): Possibly infinite wake request loop: mule.lib.evaluate_tradeoffers on entity 0x4fdfa, wake reason mask=0001 (Most likely cause: Script starts and returns immediately)
[General] 161172.12 ======================================
[General] 161172.98 ======================================
[=ERROR=] 161172.98 AIDirector::Move(): Possibly infinite wake request loop: mule.lib.evaluate_tradeoffers on entity 0x4f74e, wake reason mask=0001 (Most likely cause: Script starts and returns immediately)
[General] 161172.98 ======================================
[General] 161172.98 ======================================
[=ERROR=] 161172.98 AIDirector::Move(): Possibly infinite wake request loop: mule.lib.evaluate_tradeoffers on entity 0x4f66f, wake reason mask=0001 (Most likely cause: Script starts and returns immediately)
[General] 161172.98 ======================================`

**To Reproduce**
Steps to reproduce the behaviour:
1. Have some mules idling, probably? I have anywhere between 0-30 usually.
2. Wait

**Expected Behaviour**
The game should not hang intermittently at all :)

**Version Info (please complete the following information):**
 - X4 Foundations : 3.2
 - Mules Extended Mod : Whatever Steam had on June 18 morning UTC (it doesn't say apparently?)
 - I downloaded the mod from: Steam

### PR DESCRIPTION
**Pull request by Galaxy-Spam**
Introduced a small fix that does mitigate the lags introducted by trade search.
More of a hotfix, since it does not fix the root of the problem.
fixes #85

### CODE REVIEW

**Comment by bhayden53** [comment]
For large search spaces, won't a wait in that location cause the mule to take 30-60 seconds to evaluate trades?

**Review by Misunderstood-Wookiee — CHANGES_REQUESTED** [review]
Wait 1ms since version 2 is this fix for #85 ?
Probably should have tried a scan tick delay, 

 I'll have to test it when I'm back as I don't think I should merge this until I'm home to publish something as I'm. Not sure what this will so to trade evulation times. I still think I prefer my concept of a running loop and a idle loop where the latter goes into effect when mule has nothing to do it drastically slows the evulation rate until the next time it finds a trade then it kick the mule logic back into the running loop with a shorter delay with a max time it can be doing nothing before it kicks back down into the idle loop.

**Comment by bhayden53** [comment]
the 1ms wait simply triggers another frame, so that all of the mule's loops are not occuring in a single frame, which is what causes the noticeable freezing.

**Comment by Misunderstood-Wookiee** [comment]
Apprently it didn't fix the issue according to the issue tracker with an update after testing it so I making sure he tried to Dev build not presume it update on its own. 

It might work with a frame delay but 1 frame is probably not enough when you have a slower CPU it's likely to miss frames so 2ms may have been better to allow any back logged logic to clear out.

I'm too sure on that been needed though but I don't know if it will make it worse either just thinking about if 1ms is skip 1 frame then skipping 2 frames would help account for a CPU which already is behind frames

**Comment by Galaxy-Spam** [comment]
Corret, the 1ms will just enable another frame to trigger. 
Basically pausing the script until the next frame.
At 300 Trades and 30fps, it can delay the evaluation by up to 10s. 
In most cases mules that don't idle only evaluate 10-20 trades in my experience.
And if it's already idling, a couple of seconds is fine as a hotfix in my opinion. (Which would be the same if we use scan ticks)

@Probablynotpotato did test it and it did work initalliy, but could not prevent lags for large amount of mules later.
I think i placed the frame delay at the wrong position. 
It should be placed be in the inner loop, but somewhere at the beginning. 
Because right now it will just cause mules that found a possible trade to skip 1 frame.

I think a different approch would be nice to smooth out the CPU usage, but that does require a major update and can't be done quickly (which i think is needed in this case).
I might have some time on the weekend, but i wont have time to implement any scan tick stuff for a couple of weeks, since i would need a full weekend to code it and test it.

**Comment by Misunderstood-Wookiee** [comment]
Oh right, well should we position this in a better part of the loop? Then I'll throw the hotifx out and sort out a better solution when time allows ?

**Comment by Misunderstood-Wookiee** [comment]
I am just going to merge this and push and update as this is better than zero fixes for now, given the limited time we have right now I would rather get something out there.

**Comment by probablynotpotato** [comment]
I assume this is what @Galaxy-Spam sent me before? If yes, it's what I was using before.
I have lots of traders to try things on, let me know if there's anything to test.

**Comment by Vectorial1024** [comment]
Just walking by, but I was thinking, is it possible to do `<wait min="10ms" max="500ms" />`? I did something similar in Civilian Fleets (but it is something like `<delay min="100ms" max="5s" />` in MD-scripts instead) to spread out order sync to prevent lag spikes.

**Comment by bhayden53** [comment]
I have seen search spaces as large as 70,000 trade pairs. I think we want the waits to be small.

Random side note; I actually like what DeadAir did with the scantickrate in TaterTrader. The length of the wait is pilot-skill dependent, so that better pilots finish their trade-finding faster.

**Comment by Galaxy-Spam** [comment]
I think we should aim for a scan tick rate.
But we should keep in mind that 70 000 trade pairs are gonna take quite long, no matter how we do it.
And if multiple mules search at the same time, all evaluating 70 000 trade paris, there will be quite quickly a point where there is to much going on despite any tick rate.
The alternative would be to queue mule searches globally, with the drawback that it could take extermly long until mules react but we wont see any laggs.

**Comment by Misunderstood-Wookiee** [comment]
Hmm..
This is a tough one.
Maybe we have accept a lot of mules is too many.

**Comment by probablynotpotato** [comment]
Would it be possible eliminate a chunk of the offers based on various conditions before comparison? Assuming alternatives exist, offers too low in quantity could be discarded, offers too far could be discarded. TaterTrader does this based on relative prices.

Since supply mules aren't primarily profit-oriented, searching in small chunks and stopping at closest match for our demand could be an option. This could be an acceptable loss in material cost for overall CPU cost and incidentally higher trade throughput.

**Comment by bhayden53** [comment]
There are definitely some options, but they all require another refactor. One of the problems with the way we do things in mules is that we search for buy and sell offers totally separately, and then pair them up in a big nested loop. Some vanilla scripts and major parts of tater search for buy offers in each loop index over the sell offers. The way we've separated out the libraries in mules, switching to something else is another major refactor. 

The best way to limit the number of trades needed to evaluate for the current implementation is the limit the number of jumps, wares, or types of trades on a mule. Basically just using the available options to limit the number of trades. 

It could be possible to do some filtering at the calls to find_<buy/sell>_offer, but it would take quite a bit of testing to make sure we pick the right things to filter on and pick good values. 

Certainly we've thought through a lot of these ideas already, and at some point we'll have to pick one and just do it.

**Pull request merged**
