### PR TITLE
addition of searchDepth param for supply mule

### PR DESCRIPTION
**Pull request by bhayden53**
- supply mule has a new param called "search depth"
- at 100%, evaluates all trades. if less than 100%, reduces the size of the trade lists for performance reasons
- lists are shuffled before trimming, so if the mule doesn't find trades, they still may in a future run of the script
- existing mules will be automatically patched to add the new param at 100%
- NOTE: Some lag spikes are still possible in large search spaces. Typical culprits are a large number of jumps, and allowing AI suppliers. Based on the way we retrieve trade offers from the game, this may still cause you problems if those params allow a lot of stations. 
- NOTE: Another source of lag spikes seems to be mimics. Be a little cautious with them and experiment if they're causing you problems.

### CODE REVIEW

**Comment by bhayden53** [comment]
@Misunderstood-Wookiee still needs language update for l086

**Comment by bhayden53** [comment]
addresses #161

**Comment by Misunderstood-Wookiee** [comment]
> @Misunderstood-Wookiee still needs a language update for l086

Is that a non English language I suppose I can manage that 📦

**Comment by bhayden53** [comment]
yes non-english, not sure who supplied it originally

**Pull request merged**
