### PR TITLE
Prevent Supply Mules from disbanding the fleet if Civilian Fleets is loaded

### PR DESCRIPTION
**Pull request by Vectorial1024**
This allows Civilian Fleets to manage order syncing.

### CODE REVIEW

**Comment by Vectorial1024** [comment]
See also https://github.com/Vectorial1024/v1024_civilian_fleets/pull/16

**Comment by bhayden53** [comment]
testing now with/without civ fleets, trying to sneak into bugfix release today

**Comment by bhayden53** [comment]
@Vectorial1024 attempting to test this with Civ Fleets activated and the Trader option isn't showing up for me. I have both SirNukes and the G workaround and right click API installed (different mods depend on both, unfortunately). 

I have this in my debug log:
```
[=ERROR=] 473493.37 extensions\v1024_civilian_fleets\md\v1024_civilian_fleets.xml(115): Error while parsing expression: Operator expected
* Input: 'V1024-CF: Civilian Fleets has successfully detected SirNukes' Mod Support API.'
* Pos:                                                                  ^^^
[General] 473493.37 ======================================
[General] 473493.37 ======================================
[=ERROR=] 473493.37 Error in MD cue md.V1024_CivilianFleets.Register_CivilianFleets_RightClickMenu: Property lookup failed: md.Right_click_api
* Expression: md.Right_click_api.RegisterRight_click_api
[General] 473493.37 ======================================
[General] 473493.37 ======================================
[=ERROR=] 473493.37 Error in MD cue md.V1024_CivilianFleets.Register_CivilianFleets_RightClickMenu: Evaluated value 'null' is not of type cue
* Expression: md.Right_click_api.RegisterRight_click_api
```

**Comment by bhayden53** [comment]
Ok, my bad, I didn't actually have right-click API installed, just G workaround.

**Comment by Vectorial1024** [comment]
Still, the "expected operator" is a minor error that I have overlooked. That bug only affected the announcement scripts, and does not affect how the mod functions.

**Comment by bhayden53** [comment]
Patch to mules works fine. Worth mentioning that it looks like somehow the $maxDist setting is coming up Null when managed by civ fleets. In the mules order transfer loop I use the formula:
```
<param name="maxDist" value="[$subordinate.pilot.skill.piloting * 2, $maxDist].min" />
```

**Pull request merged**
